# 设置通用的变量
nginx_version: "1.26.2"


mysql_root_password: "your_secure_password"


php_version: "8.2.24"


libiconv_ver=1.16
curl_ver=8.8.0
libmcrypt_ver=2.5.8
mcrypt_ver=2.6.8
mhash_ver=0.9.9.9
freetype_ver=2.10.1
icu4c_ver=63_1
libsodium_ver=1.0.20
libzip_ver=1.2.0
argon2_ver=20171227
binutils_ver=2.42
imagemagick_ver=7.1.1-39
imagick_ver=3.7.0
imagick_oldver=3.4.4
graphicsmagick_ver=1.3.40
gmagick_ver=2.0.6RC1
gmagick_oldver=1.1.7RC3
zendopcache_ver=7.0.5
apcu_ver=5.1.23
apcu_oldver=4.0.11
xcache_ver=3.2.0
eaccelerator_ver=0.9.6.1
phalcon_ver=5.4.0
phalcon_oldver=3.4.5
yaf_ver=3.3.2
yar_ver=2.2.0
swoole_ver=5.0.3
swoole_oldver=4.8.12
xdebug_ver=3.1.2
xdebug_oldver=2.9.8
pecl_redis_ver=6.0.2