- name: 安装 Nginx
  ansible.builtin.apt:
    name: nginx
    state: "{{ nginx_version }}"
    update_cache: yes

- name: 配置 Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: 启动并启用 Nginx 服务
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

handlers:
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
