# Handlers
handlers:
  - name: enable lzf extension
    ansible.builtin.command: phpenmod lzf

  - name: restart PHP-FPM
    ansible.builtin.service:
      name: "php{{ php_version }}-fpm"
      state: restarted
