- name: 添加 PHP Sury GPG 密钥
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: 添加 Sury PPA 所需依赖
  ansible.builtin.apt:
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: 添加 PHP Sury PPA 源
  ansible.builtin.apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_facts['lsb']['codename'] }} main"
    state: present
    filename: "php-sury"
    validate_certs: yes

- name: 更新包缓存
  ansible.builtin.apt:
    update_cache: yes
  when: add_repo is changed

- name: 确认 PHP 版本是否可用
  ansible.builtin.apt:
    name: "php{{ php_version }}"
    state: present
  register: php_install_check
  ignore_errors: yes

- name: 失败时提示 PHP 版本不可用
  ansible.builtin.fail:
    msg: "指定的 PHP 版本 {{ php_version }} 不可用，请检查版本号或包源。"
  when: php_install_check is failed

- name: 安装 PHP 和扩展
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-mysql"
      - libxml2
    state: present
  when: php_install_check is succeeded

- name: 启动并启用 PHP-FPM 服务
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true
  when: php_install_check is succeeded
