- name: 更新软件包列表
  ansible.builtin.apt:
    update_cache: yes

- name: 安装 PHP 及所有扩展模块
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ php_modules }}"

- name: 安装 PECL 和 PHP 开发工具
  ansible.builtin.apt:
    name:
      - php-pear
      - "php{{ php_version }}-dev"
    state: present

- name: 更新 PECL 渠道
  ansible.builtin.shell: pecl channel-update pecl.php.net

- name: 检查 PECL 是否已安装 lzf 模块
  ansible.builtin.shell: "pecl list | grep -E '^lzf '"
  register: pecl_lzf_check
  changed_when: false
  failed_when: false

- name: 使用 PECL 安装 lzf 模块（仅在未安装时）
  ansible.builtin.shell: |
    printf "no\n" | pecl install lzf
  args:
    creates: "/usr/lib/php/$(php -r 'echo PHP_MAJOR_VERSION.\".\".PHP_MINOR_VERSION;')/lzf.so"
  when: pecl_lzf_check.rc != 0  # 仅当 PECL 未找到 lzf 模块时执行
  notify: restart php-fpm

- name: 启用 lzf 模块
  ansible.builtin.shell: |
    echo "extension=lzf.so" > {{ php_extensions_dir }}/lzf.ini
  notify: restart php-fpm
  when: pecl_lzf_check.rc != 0  # 仅当 PECL 未找到 lzf 模块时执行

- name: 验证 lzf 模块是否已加载
  ansible.builtin.shell: "php -m | grep -E '^lzf$'"
  register: lzf_verification
  changed_when: false
  failed_when: lzf_verification.rc != 0

- name: 安装 Git 以下载 snappy 源码
  ansible.builtin.apt:
    name: git
    state: present

- name: 克隆 snappy 扩展源码
  ansible.builtin.git:
    repo: "{{ php_snappy_repo }}"
    dest: /tmp/php-ext-snappy
    version: HEAD
    depth: 1

- name: 编译并安装 snappy 扩展
  ansible.builtin.shell: |
    cd /tmp/php-ext-snappy
    phpize
    ./configure
    make
    make install
  args:
    creates: "/usr/lib/php/$(php -r 'echo PHP_MAJOR_VERSION.\".\".PHP_MINOR_VERSION;')/snappy.so"

- name: 启用 snappy 扩展
  ansible.builtin.shell: |
    echo "extension=snappy.so" > {{ php_extensions_dir }}/snappy.ini
  notify: restart php-fpm

- name: 清理 snappy 源码目录
  ansible.builtin.file:
    path: /tmp/php-ext-snappy
    state: absent

- name: 验证 lzf 模块是否已加载
  ansible.builtin.shell: "php -m | grep -E '^lzf$'"
  register: lzf_check
  changed_when: false
  failed_when: lzf_check.rc != 0
  ignore_errors: no

- name: 验证 snappy 模块是否已加载
  ansible.builtin.shell: "php -m | grep -E '^snappy$'"
  register: snappy_check
  changed_when: false
  failed_when: snappy_check.rc != 0
  ignore_errors: no
