- name: 更新软件包列表
  ansible.builtin.apt:
    update_cache: yes

- name: 安装 PHP 稳定版和基础组件
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
    state: present

- name: 安装常用 PHP 扩展
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-apcu"
      - "php{{ php_version }}-redis"
      - "php{{ php_version }}-imagick"
      - libxml2
      - php-pear
      - "php{{ php_version }}-dev"
    state: present

- name: 使用 PECL 安装 lzf 扩展
  ansible.builtin.shell: |
    pecl install lzf
  args:
    creates: /usr/lib/php/$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')/lzf.so
  notify: enable lzf extension

- name: 启用 lzf 扩展
  ansible.builtin.shell: |
    echo "extension=lzf.so" > /etc/php/{{ php_version }}/mods-available/lzf.ini
  notify: phpenmod lzf
  when: ansible_facts['os_family'] == "Debian"

- name: 启用 lzf 扩展模块
  ansible.builtin.command: phpenmod lzf
  when: ansible_facts['os_family'] == "Debian"

- name: 启动并启用 PHP-FPM 服务
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true

# Handlers
handlers:
  - name: enable lzf extension
    ansible.builtin.command: phpenmod lzf

  - name: restart PHP-FPM
    ansible.builtin.service:
      name: "php{{ php_version }}-fpm"
      state: restarted
